/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer
 * listed in this license in the documentation and/or other materials
 * provided with the distribution.
 * 
 * Neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * 
 * The copyright holders provide no reassurances that the source code
 * provided does not infringe any patent, copyright, or any other
 * intellectual property rights of third parties. The copyright holders
 * disclaim any liability to any recipient for claims brought against
 * recipient by any third party for infringement of that parties
 * intellectual property rights.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @file     E:/Workshop/Work_in_progress/14_Evalbot/lm3s9b92.h
 * @brief    CMSIS HeaderFile
 * @version  1.2
 * @date     Sat Apr 11 16:44:02 2026
 * @note     Generated by SVDConv V3.3.49
 *           from File 'E:/Workshop/Work_in_progress/14_Evalbot/lm3s9b92.svd',
 *           last modified on Sat Apr 11 16:39:40 2026
 */


/** @addtogroup Texas Instruments Inc.
  * @{
  */


/** @addtogroup lm3s9b92
  * @{
  */


#ifndef LM3S9B92_H
#define LM3S9B92_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M3 Specific Interrupt Numbers  ======================================== */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  MemoryManagement_IRQn     = -12,              /*!< -12  Memory Management, MPU mismatch, including Access Violation
                                                     and No Match                                                              */
  BusFault_IRQn             = -11,              /*!< -11  Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory
                                                     related Fault                                                             */
  UsageFault_IRQn           = -10,              /*!< -10  Usage Fault, i.e. Undef Instruction, Illegal State Transition        */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  DebugMonitor_IRQn         =  -4,              /*!< -4 Debug Monitor                                                          */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* ==========================================  lm3s9b92 Specific Interrupt Numbers  ========================================== */
  WDT0_IRQn                 =   0,              /*!< 0  Watchdog Timer 0 interrupt.                                            */
  WDT1_IRQn                 =   1               /*!< 1  Watchdog Timer 1 interrupt.                                            */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ===========================  Configuration of the ARM Cortex-M3 Processor and Core Peripherals  =========================== */
#define __CM3_REV                 0x0200U       /*!< CM3 Core Revision                                                         */
#define __NVIC_PRIO_BITS               3        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __MPU_PRESENT                  0        /*!< MPU present                                                               */
#define __FPU_PRESENT                  0        /*!< FPU present                                                               */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm3.h"                           /*!< ARM Cortex-M3 processor and core peripherals                              */
#include "system_lm3s9b92.h"                    /*!< lm3s9b92 System                                                           */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           WDT0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Watchdog timer 0, with 32-bit down counter (WDT0)
  */

typedef struct {                                /*!< WDT0 Structure                                                            */
  __IOM uint32_t  WDTLOAD;                      /*!< 32-bit interval value used by the 32-bit watchdog down-counter.           */
  __IOM uint32_t  WDTVALUE;                     /*!< 32-bit register with the current count value of the timer.                */
  __IOM uint32_t  WDTCTL;                       /*!< Watchdog Control Register.                                                */
  __OM  uint32_t  ICR;                          /*!< Watchdog Interrupt Clear Register.                                        */
  __IOM uint32_t  RIS;                          /*!< Watchdog Raw Interrupt Status Register.                                   */
  __IOM uint32_t  WDTMIS;                       /*!< Watchdog Masked Interrupt Status Register.                                */
  __IM  uint32_t  RESERVED[256];
  __IOM uint32_t  WDTTEST;                      /*!< Watchdog Test Register.                                                   */
  __IM  uint32_t  RESERVED1[505];
  __IOM uint32_t  WDTLOCK;                      /*!< Watchdog Lock Register.                                                   */
} WDT0_Type;                                    /*!< Size = 3076 (0xc04)                                                       */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define WDT0_BASE                   0x40000000UL
#define WDT1_BASE                   0x40001000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define WDT0                        ((WDT0_Type*)              WDT0_BASE)
#define WDT1                        ((WDT0_Type*)              WDT1_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================================================================================================== */
/* ================                                Pos/Mask Peripheral Section                                ================ */
/* =========================================================================================================================== */


/** @addtogroup PosMask_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           WDT0                                            ================ */
/* =========================================================================================================================== */

/* ========================================================  WDTLOAD  ======================================================== */
/* =======================================================  WDTVALUE  ======================================================== */
/* ========================================================  WDTCTL  ========================================================= */
#define WDT0_WDTCTL_WRC_Pos               (31UL)                    /*!< WRC (Bit 31)                                          */
#define WDT0_WDTCTL_WRC_Msk               (0x80000000UL)            /*!< WRC (Bitfield-Mask: 0x01)                             */
#define WDT0_WDTCTL_RESEN_Pos             (1UL)                     /*!< RESEN (Bit 1)                                         */
#define WDT0_WDTCTL_RESEN_Msk             (0x2UL)                   /*!< RESEN (Bitfield-Mask: 0x01)                           */
#define WDT0_WDTCTL_INTEN_Pos             (0UL)                     /*!< INTEN (Bit 0)                                         */
#define WDT0_WDTCTL_INTEN_Msk             (0x1UL)                   /*!< INTEN (Bitfield-Mask: 0x01)                           */
/* ==========================================================  ICR  ========================================================== */
/* ==========================================================  RIS  ========================================================== */
#define WDT0_RIS_WDTRIS_Pos               (0UL)                     /*!< WDTRIS (Bit 0)                                        */
#define WDT0_RIS_WDTRIS_Msk               (0x1UL)                   /*!< WDTRIS (Bitfield-Mask: 0x01)                          */
/* ========================================================  WDTMIS  ========================================================= */
#define WDT0_WDTMIS_WDTMIS_Pos            (0UL)                     /*!< WDTMIS (Bit 0)                                        */
#define WDT0_WDTMIS_WDTMIS_Msk            (0x1UL)                   /*!< WDTMIS (Bitfield-Mask: 0x01)                          */
/* ========================================================  WDTTEST  ======================================================== */
#define WDT0_WDTTEST_STALL_Pos            (8UL)                     /*!< STALL (Bit 8)                                         */
#define WDT0_WDTTEST_STALL_Msk            (0x100UL)                 /*!< STALL (Bitfield-Mask: 0x01)                           */
/* ========================================================  WDTLOCK  ======================================================== */
#define WDT0_WDTLOCK_WDTLOCK_Pos          (0UL)                     /*!< WDTLOCK (Bit 0)                                       */
#define WDT0_WDTLOCK_WDTLOCK_Msk          (0x1UL)                   /*!< WDTLOCK (Bitfield-Mask: 0x01)                         */

/** @} */ /* End of group PosMask_peripherals */


#ifdef __cplusplus
}
#endif

#endif /* LM3S9B92_H */


/** @} */ /* End of group lm3s9b92 */

/** @} */ /* End of group Texas Instruments Inc. */
