/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer
 * listed in this license in the documentation and/or other materials
 * provided with the distribution.
 * 
 * Neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * 
 * The copyright holders provide no reassurances that the source code
 * provided does not infringe any patent, copyright, or any other
 * intellectual property rights of third parties. The copyright holders
 * disclaim any liability to any recipient for claims brought against
 * recipient by any third party for infringement of that parties
 * intellectual property rights.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @file     E:/Workshop/Work_in_progress/36_EvalbotPack/LM3S9B92-CMSIS-DFP/Sources/Core/inc/lm3s9b92.h
 * @brief    CMSIS HeaderFile
 * @version  1.2
 * @date     Sat May 30 14:28:40 2026
 * @note     Generated by SVDConv V3.3.50
 *           from File 'E:/Workshop/Work_in_progress/36_EvalbotPack/LM3S9B92-CMSIS-DFP/SVD/lm3s9b92.svd',
 *           last modified on Sat May 30 14:28:35 2026
 */


/** @addtogroup Texas Instruments Inc.
  * @{
  */


/** @addtogroup lm3s9b92
  * @{
  */


#ifndef LM3S9B92_H
#define LM3S9B92_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M3 Specific Interrupt Numbers  ======================================== */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  MemoryManagement_IRQn     = -12,              /*!< -12  Memory Management, MPU mismatch, including Access Violation
                                                     and No Match                                                              */
  BusFault_IRQn             = -11,              /*!< -11  Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory
                                                     related Fault                                                             */
  UsageFault_IRQn           = -10,              /*!< -10  Usage Fault, i.e. Undef Instruction, Illegal State Transition        */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  DebugMonitor_IRQn         =  -4,              /*!< -4 Debug Monitor                                                          */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* ==========================================  lm3s9b92 Specific Interrupt Numbers  ========================================== */
  GPIOA_IRQn                =   0,              /*!< 0  GPIO A interrupt.                                                      */
  GPIOB_IRQn                =   1,              /*!< 1  GPIO B interrupt.                                                      */
  GPIOC_IRQn                =   2,              /*!< 2  GPIO C interrupt.                                                      */
  GPIOD_IRQn                =   3,              /*!< 3  GPIO D interrupt.                                                      */
  GPIOE_IRQn                =   4,              /*!< 4  GPIO E interrupt.                                                      */
  WDT0_IRQn                 =  18,              /*!< 18 Watchdog Timer 0 and 1 interrupt.                                      */
  SYSCTL_IRQn               =  28,              /*!< 28 System Control interrupt.                                              */
  GPIOF_IRQn                =  30,              /*!< 30 GPIO F interrupt.                                                      */
  GPIOG_IRQn                =  31,              /*!< 31 GPIO G interrupt.                                                      */
  GPIOH_IRQn                =  32,              /*!< 32 GPIO H interrupt.                                                      */
  GPIOJ_IRQn                =  54               /*!< 54 GPIO J interrupt.                                                      */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ===========================  Configuration of the ARM Cortex-M3 Processor and Core Peripherals  =========================== */
#define __CM3_REV                 0x0200U       /*!< CM3 Core Revision                                                         */
#define __NVIC_PRIO_BITS               3        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __MPU_PRESENT                  0        /*!< MPU present                                                               */
#define __FPU_PRESENT                  0        /*!< FPU present                                                               */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm3.h"                           /*!< ARM Cortex-M3 processor and core peripherals                              */
#include "system_lm3s9b92.h"                    /*!< lm3s9b92 System                                                           */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           GPIOA                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief Register map for GPIO PORT A peripheral. (GPIOA)
  */

typedef struct {                                /*!< GPIOA Structure                                                           */
  __IOM uint32_t  DATA[256];                    /*!< Data of GPIO Port.                                                        */
  __IOM uint32_t  DIR;                          /*!< Directions of GPIO Port pins.                                             */
  __IOM uint32_t  IS;                           /*!< GPIO Interrupt Sense.                                                     */
  __IOM uint32_t  IBE;                          /*!< GPIO Interrupt Both Edges.                                                */
  __IOM uint32_t  IEV;                          /*!< GPIO Interrupt Event.                                                     */
  __IOM uint32_t  IM;                           /*!< GPIO Interrupt Mask.                                                      */
  __IM  uint32_t  RIS;                          /*!< GPIO Raw Interrupt Status.                                                */
  __IM  uint32_t  MIS;                          /*!< GPIO Mask Interrupt Status.                                               */
  __OM  uint32_t  IC;                           /*!< GPIO Interrupt Clear.                                                     */
  __IOM uint32_t  AFSEL;                        /*!< GPIO Alternate Function Select.                                           */
  __IM  uint32_t  RESERVED[55];
  __IOM uint32_t  DR2R;                         /*!< GPIO 2-mA Drive Select.                                                   */
  __IOM uint32_t  DR4R;                         /*!< GPIO 4-mA Drive Select.                                                   */
  __IOM uint32_t  DR8R;                         /*!< GPIO 8-mA Drive Select.                                                   */
  __IOM uint32_t  ODR;                          /*!< GPIO Open Drain Select.                                                   */
  __IOM uint32_t  PUR;                          /*!< GPIO Pull-Up Select.                                                      */
  __IOM uint32_t  PDR;                          /*!< GPIO Pull-Down Select.                                                    */
  __IOM uint32_t  SLR;                          /*!< GPIO Slew Rate Control Select.                                            */
  __IOM uint32_t  DEN;                          /*!< GPIO Digital Enable.                                                      */
  __IOM uint32_t  LOCK;                         /*!< GPIO Lock.                                                                */
  __IOM uint32_t  CR;                           /*!< GPIO Commit Register.                                                     */
  __IOM uint32_t  AMSEL;                        /*!< GPIO Analog Mode Select.                                                  */
  __IOM uint32_t  PCTL;                         /*!< GPIO Port Control.                                                        */
  __IM  uint32_t  RESERVED1[680];
  __IM  uint32_t  PeriphID4;                    /*!< GPIO Peripheral Identification 4.                                         */
  __IM  uint32_t  PeriphID5;                    /*!< GPIO Peripheral Identification 5.                                         */
  __IM  uint32_t  PeriphID6;                    /*!< GPIO Peripheral Identification 6.                                         */
  __IM  uint32_t  PeriphID7;                    /*!< GPIO Peripheral Identification 7.                                         */
  __IM  uint32_t  PeriphID0;                    /*!< GPIO Peripheral Identification 0.                                         */
  __IM  uint32_t  PeriphID1;                    /*!< GPIO Peripheral Identification 1.                                         */
  __IM  uint32_t  PeriphID2;                    /*!< GPIO Peripheral Identification 2.                                         */
  __IM  uint32_t  PeriphID3;                    /*!< GPIO Peripheral Identification 3.                                         */
  __IM  uint32_t  PCellID0;                     /*!< GPIO PrimeCell Identification 0.                                          */
  __IM  uint32_t  PCellID1;                     /*!< GPIO PrimeCell Identification 1.                                          */
  __IM  uint32_t  PCellID2;                     /*!< GPIO PrimeCell Identification 2.                                          */
  __IM  uint32_t  PCellID3;                     /*!< GPIO PrimeCell Identification 3.                                          */
} GPIO_Type;                                    /*!< Size = 4096 (0x1000)                                                      */



/* =========================================================================================================================== */
/* ================                                           WDT0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Watchdog timer 0, with 32-bit down counter. (WDT0)
  */

typedef struct {                                /*!< WDT0 Structure                                                            */
  __IOM uint32_t  WDTLOAD;                      /*!< 32-bit interval value used by the 32-bit watchdog down-counter.           */
  __IOM uint32_t  WDTVALUE;                     /*!< 32-bit register with the current count value of the timer.                */
  __IOM uint32_t  WDTCTL;                       /*!< Watchdog Control Register.                                                */
  __OM  uint32_t  ICR;                          /*!< Watchdog Interrupt Clear Register.                                        */
  __IOM uint32_t  RIS;                          /*!< Watchdog Raw Interrupt Status Register.                                   */
  __IOM uint32_t  WDTMIS;                       /*!< Watchdog Masked Interrupt Status Register.                                */
  __IM  uint32_t  RESERVED[256];
  __IOM uint32_t  WDTTEST;                      /*!< Watchdog Test Register.                                                   */
  __IM  uint32_t  RESERVED1[505];
  __IOM uint32_t  WDTLOCK;                      /*!< Watchdog Lock Register.                                                   */
} WDT_Type;                                     /*!< Size = 3076 (0xc04)                                                       */



/* =========================================================================================================================== */
/* ================                                          SYSCTL                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief System control configures the overall operation of the device and provides information about the device. (SYSCTL)
  */

typedef struct {                                /*!< SYSCTL Structure                                                          */
  __IM  uint32_t  DID0;                         /*!< This register identifies the version of the microcontroller.              */
} SYSCTL_Type;                                  /*!< Size = 4 (0x4)                                                            */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define GPIOA_BASE                  0x40004000UL
#define GPIOB_BASE                  0x40005000UL
#define GPIOC_BASE                  0x40006000UL
#define GPIOD_BASE                  0x40007000UL
#define GPIOE_BASE                  0x40024000UL
#define GPIOF_BASE                  0x40025000UL
#define GPIOG_BASE                  0x40026000UL
#define GPIOH_BASE                  0x40027000UL
#define GPIOJ_BASE                  0x4003D000UL
#define WDT0_BASE                   0x40000000UL
#define WDT1_BASE                   0x40001000UL
#define SYSCTL_BASE                 0x400FE000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define GPIOA                       ((GPIO_Type*)              GPIOA_BASE)
#define GPIOB                       ((GPIO_Type*)              GPIOB_BASE)
#define GPIOC                       ((GPIO_Type*)              GPIOC_BASE)
#define GPIOD                       ((GPIO_Type*)              GPIOD_BASE)
#define GPIOE                       ((GPIO_Type*)              GPIOE_BASE)
#define GPIOF                       ((GPIO_Type*)              GPIOF_BASE)
#define GPIOG                       ((GPIO_Type*)              GPIOG_BASE)
#define GPIOH                       ((GPIO_Type*)              GPIOH_BASE)
#define GPIOJ                       ((GPIO_Type*)              GPIOJ_BASE)
#define WDT0                        ((WDT_Type*)               WDT0_BASE)
#define WDT1                        ((WDT_Type*)               WDT1_BASE)
#define SYSCTL                      ((SYSCTL_Type*)            SYSCTL_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================================================================================================== */
/* ================                                Pos/Mask Peripheral Section                                ================ */
/* =========================================================================================================================== */


/** @addtogroup PosMask_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           GPIO                                            ================ */
/* =========================================================================================================================== */

/* =========================================================  DATA  ========================================================== */
#define GPIO_DATA_DATA7_Pos               (7UL)                     /*!< DATA7 (Bit 7)                                         */
#define GPIO_DATA_DATA7_Msk               (0x80UL)                  /*!< DATA7 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA6_Pos               (6UL)                     /*!< DATA6 (Bit 6)                                         */
#define GPIO_DATA_DATA6_Msk               (0x40UL)                  /*!< DATA6 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA5_Pos               (5UL)                     /*!< DATA5 (Bit 5)                                         */
#define GPIO_DATA_DATA5_Msk               (0x20UL)                  /*!< DATA5 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA4_Pos               (4UL)                     /*!< DATA4 (Bit 4)                                         */
#define GPIO_DATA_DATA4_Msk               (0x10UL)                  /*!< DATA4 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA3_Pos               (3UL)                     /*!< DATA3 (Bit 3)                                         */
#define GPIO_DATA_DATA3_Msk               (0x8UL)                   /*!< DATA3 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA2_Pos               (2UL)                     /*!< DATA2 (Bit 2)                                         */
#define GPIO_DATA_DATA2_Msk               (0x4UL)                   /*!< DATA2 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA1_Pos               (1UL)                     /*!< DATA1 (Bit 1)                                         */
#define GPIO_DATA_DATA1_Msk               (0x2UL)                   /*!< DATA1 (Bitfield-Mask: 0x01)                           */
#define GPIO_DATA_DATA0_Pos               (0UL)                     /*!< DATA0 (Bit 0)                                         */
#define GPIO_DATA_DATA0_Msk               (0x1UL)                   /*!< DATA0 (Bitfield-Mask: 0x01)                           */
/* ==========================================================  DIR  ========================================================== */
#define GPIO_DIR_DIR7_Pos                 (7UL)                     /*!< DIR7 (Bit 7)                                          */
#define GPIO_DIR_DIR7_Msk                 (0x80UL)                  /*!< DIR7 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR6_Pos                 (6UL)                     /*!< DIR6 (Bit 6)                                          */
#define GPIO_DIR_DIR6_Msk                 (0x40UL)                  /*!< DIR6 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR5_Pos                 (5UL)                     /*!< DIR5 (Bit 5)                                          */
#define GPIO_DIR_DIR5_Msk                 (0x20UL)                  /*!< DIR5 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR4_Pos                 (4UL)                     /*!< DIR4 (Bit 4)                                          */
#define GPIO_DIR_DIR4_Msk                 (0x10UL)                  /*!< DIR4 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR3_Pos                 (3UL)                     /*!< DIR3 (Bit 3)                                          */
#define GPIO_DIR_DIR3_Msk                 (0x8UL)                   /*!< DIR3 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR2_Pos                 (2UL)                     /*!< DIR2 (Bit 2)                                          */
#define GPIO_DIR_DIR2_Msk                 (0x4UL)                   /*!< DIR2 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR1_Pos                 (1UL)                     /*!< DIR1 (Bit 1)                                          */
#define GPIO_DIR_DIR1_Msk                 (0x2UL)                   /*!< DIR1 (Bitfield-Mask: 0x01)                            */
#define GPIO_DIR_DIR0_Pos                 (0UL)                     /*!< DIR0 (Bit 0)                                          */
#define GPIO_DIR_DIR0_Msk                 (0x1UL)                   /*!< DIR0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  IS  =========================================================== */
#define GPIO_IS_IS7_Pos                   (7UL)                     /*!< IS7 (Bit 7)                                           */
#define GPIO_IS_IS7_Msk                   (0x80UL)                  /*!< IS7 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS6_Pos                   (6UL)                     /*!< IS6 (Bit 6)                                           */
#define GPIO_IS_IS6_Msk                   (0x40UL)                  /*!< IS6 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS5_Pos                   (5UL)                     /*!< IS5 (Bit 5)                                           */
#define GPIO_IS_IS5_Msk                   (0x20UL)                  /*!< IS5 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS4_Pos                   (4UL)                     /*!< IS4 (Bit 4)                                           */
#define GPIO_IS_IS4_Msk                   (0x10UL)                  /*!< IS4 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS3_Pos                   (3UL)                     /*!< IS3 (Bit 3)                                           */
#define GPIO_IS_IS3_Msk                   (0x8UL)                   /*!< IS3 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS2_Pos                   (2UL)                     /*!< IS2 (Bit 2)                                           */
#define GPIO_IS_IS2_Msk                   (0x4UL)                   /*!< IS2 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS1_Pos                   (1UL)                     /*!< IS1 (Bit 1)                                           */
#define GPIO_IS_IS1_Msk                   (0x2UL)                   /*!< IS1 (Bitfield-Mask: 0x01)                             */
#define GPIO_IS_IS0_Pos                   (0UL)                     /*!< IS0 (Bit 0)                                           */
#define GPIO_IS_IS0_Msk                   (0x1UL)                   /*!< IS0 (Bitfield-Mask: 0x01)                             */
/* ==========================================================  IBE  ========================================================== */
#define GPIO_IBE_IBE7_Pos                 (7UL)                     /*!< IBE7 (Bit 7)                                          */
#define GPIO_IBE_IBE7_Msk                 (0x80UL)                  /*!< IBE7 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE6_Pos                 (6UL)                     /*!< IBE6 (Bit 6)                                          */
#define GPIO_IBE_IBE6_Msk                 (0x40UL)                  /*!< IBE6 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE5_Pos                 (5UL)                     /*!< IBE5 (Bit 5)                                          */
#define GPIO_IBE_IBE5_Msk                 (0x20UL)                  /*!< IBE5 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE4_Pos                 (4UL)                     /*!< IBE4 (Bit 4)                                          */
#define GPIO_IBE_IBE4_Msk                 (0x10UL)                  /*!< IBE4 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE3_Pos                 (3UL)                     /*!< IBE3 (Bit 3)                                          */
#define GPIO_IBE_IBE3_Msk                 (0x8UL)                   /*!< IBE3 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE2_Pos                 (2UL)                     /*!< IBE2 (Bit 2)                                          */
#define GPIO_IBE_IBE2_Msk                 (0x4UL)                   /*!< IBE2 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE1_Pos                 (1UL)                     /*!< IBE1 (Bit 1)                                          */
#define GPIO_IBE_IBE1_Msk                 (0x2UL)                   /*!< IBE1 (Bitfield-Mask: 0x01)                            */
#define GPIO_IBE_IBE0_Pos                 (0UL)                     /*!< IBE0 (Bit 0)                                          */
#define GPIO_IBE_IBE0_Msk                 (0x1UL)                   /*!< IBE0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  IEV  ========================================================== */
#define GPIO_IEV_IEV7_Pos                 (7UL)                     /*!< IEV7 (Bit 7)                                          */
#define GPIO_IEV_IEV7_Msk                 (0x80UL)                  /*!< IEV7 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV6_Pos                 (6UL)                     /*!< IEV6 (Bit 6)                                          */
#define GPIO_IEV_IEV6_Msk                 (0x40UL)                  /*!< IEV6 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV5_Pos                 (5UL)                     /*!< IEV5 (Bit 5)                                          */
#define GPIO_IEV_IEV5_Msk                 (0x20UL)                  /*!< IEV5 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV4_Pos                 (4UL)                     /*!< IEV4 (Bit 4)                                          */
#define GPIO_IEV_IEV4_Msk                 (0x10UL)                  /*!< IEV4 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV3_Pos                 (3UL)                     /*!< IEV3 (Bit 3)                                          */
#define GPIO_IEV_IEV3_Msk                 (0x8UL)                   /*!< IEV3 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV2_Pos                 (2UL)                     /*!< IEV2 (Bit 2)                                          */
#define GPIO_IEV_IEV2_Msk                 (0x4UL)                   /*!< IEV2 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV1_Pos                 (1UL)                     /*!< IEV1 (Bit 1)                                          */
#define GPIO_IEV_IEV1_Msk                 (0x2UL)                   /*!< IEV1 (Bitfield-Mask: 0x01)                            */
#define GPIO_IEV_IEV0_Pos                 (0UL)                     /*!< IEV0 (Bit 0)                                          */
#define GPIO_IEV_IEV0_Msk                 (0x1UL)                   /*!< IEV0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  IM  =========================================================== */
#define GPIO_IM_IME7_Pos                  (7UL)                     /*!< IME7 (Bit 7)                                          */
#define GPIO_IM_IME7_Msk                  (0x80UL)                  /*!< IME7 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME6_Pos                  (6UL)                     /*!< IME6 (Bit 6)                                          */
#define GPIO_IM_IME6_Msk                  (0x40UL)                  /*!< IME6 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME5_Pos                  (5UL)                     /*!< IME5 (Bit 5)                                          */
#define GPIO_IM_IME5_Msk                  (0x20UL)                  /*!< IME5 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME4_Pos                  (4UL)                     /*!< IME4 (Bit 4)                                          */
#define GPIO_IM_IME4_Msk                  (0x10UL)                  /*!< IME4 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME3_Pos                  (3UL)                     /*!< IME3 (Bit 3)                                          */
#define GPIO_IM_IME3_Msk                  (0x8UL)                   /*!< IME3 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME2_Pos                  (2UL)                     /*!< IME2 (Bit 2)                                          */
#define GPIO_IM_IME2_Msk                  (0x4UL)                   /*!< IME2 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME1_Pos                  (1UL)                     /*!< IME1 (Bit 1)                                          */
#define GPIO_IM_IME1_Msk                  (0x2UL)                   /*!< IME1 (Bitfield-Mask: 0x01)                            */
#define GPIO_IM_IME0_Pos                  (0UL)                     /*!< IME0 (Bit 0)                                          */
#define GPIO_IM_IME0_Msk                  (0x1UL)                   /*!< IME0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  RIS  ========================================================== */
#define GPIO_RIS_RIS7_Pos                 (7UL)                     /*!< RIS7 (Bit 7)                                          */
#define GPIO_RIS_RIS7_Msk                 (0x80UL)                  /*!< RIS7 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS6_Pos                 (6UL)                     /*!< RIS6 (Bit 6)                                          */
#define GPIO_RIS_RIS6_Msk                 (0x40UL)                  /*!< RIS6 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS5_Pos                 (5UL)                     /*!< RIS5 (Bit 5)                                          */
#define GPIO_RIS_RIS5_Msk                 (0x20UL)                  /*!< RIS5 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS4_Pos                 (4UL)                     /*!< RIS4 (Bit 4)                                          */
#define GPIO_RIS_RIS4_Msk                 (0x10UL)                  /*!< RIS4 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS3_Pos                 (3UL)                     /*!< RIS3 (Bit 3)                                          */
#define GPIO_RIS_RIS3_Msk                 (0x8UL)                   /*!< RIS3 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS2_Pos                 (2UL)                     /*!< RIS2 (Bit 2)                                          */
#define GPIO_RIS_RIS2_Msk                 (0x4UL)                   /*!< RIS2 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS1_Pos                 (1UL)                     /*!< RIS1 (Bit 1)                                          */
#define GPIO_RIS_RIS1_Msk                 (0x2UL)                   /*!< RIS1 (Bitfield-Mask: 0x01)                            */
#define GPIO_RIS_RIS0_Pos                 (0UL)                     /*!< RIS0 (Bit 0)                                          */
#define GPIO_RIS_RIS0_Msk                 (0x1UL)                   /*!< RIS0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  MIS  ========================================================== */
#define GPIO_MIS_MIS7_Pos                 (7UL)                     /*!< MIS7 (Bit 7)                                          */
#define GPIO_MIS_MIS7_Msk                 (0x80UL)                  /*!< MIS7 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS6_Pos                 (6UL)                     /*!< MIS6 (Bit 6)                                          */
#define GPIO_MIS_MIS6_Msk                 (0x40UL)                  /*!< MIS6 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS5_Pos                 (5UL)                     /*!< MIS5 (Bit 5)                                          */
#define GPIO_MIS_MIS5_Msk                 (0x20UL)                  /*!< MIS5 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS4_Pos                 (4UL)                     /*!< MIS4 (Bit 4)                                          */
#define GPIO_MIS_MIS4_Msk                 (0x10UL)                  /*!< MIS4 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS3_Pos                 (3UL)                     /*!< MIS3 (Bit 3)                                          */
#define GPIO_MIS_MIS3_Msk                 (0x8UL)                   /*!< MIS3 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS2_Pos                 (2UL)                     /*!< MIS2 (Bit 2)                                          */
#define GPIO_MIS_MIS2_Msk                 (0x4UL)                   /*!< MIS2 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS1_Pos                 (1UL)                     /*!< MIS1 (Bit 1)                                          */
#define GPIO_MIS_MIS1_Msk                 (0x2UL)                   /*!< MIS1 (Bitfield-Mask: 0x01)                            */
#define GPIO_MIS_MIS0_Pos                 (0UL)                     /*!< MIS0 (Bit 0)                                          */
#define GPIO_MIS_MIS0_Msk                 (0x1UL)                   /*!< MIS0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  IC  =========================================================== */
#define GPIO_IC_IC7_Pos                   (7UL)                     /*!< IC7 (Bit 7)                                           */
#define GPIO_IC_IC7_Msk                   (0x80UL)                  /*!< IC7 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC6_Pos                   (6UL)                     /*!< IC6 (Bit 6)                                           */
#define GPIO_IC_IC6_Msk                   (0x40UL)                  /*!< IC6 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC5_Pos                   (5UL)                     /*!< IC5 (Bit 5)                                           */
#define GPIO_IC_IC5_Msk                   (0x20UL)                  /*!< IC5 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC4_Pos                   (4UL)                     /*!< IC4 (Bit 4)                                           */
#define GPIO_IC_IC4_Msk                   (0x10UL)                  /*!< IC4 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC3_Pos                   (3UL)                     /*!< IC3 (Bit 3)                                           */
#define GPIO_IC_IC3_Msk                   (0x8UL)                   /*!< IC3 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC2_Pos                   (2UL)                     /*!< IC2 (Bit 2)                                           */
#define GPIO_IC_IC2_Msk                   (0x4UL)                   /*!< IC2 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC1_Pos                   (1UL)                     /*!< IC1 (Bit 1)                                           */
#define GPIO_IC_IC1_Msk                   (0x2UL)                   /*!< IC1 (Bitfield-Mask: 0x01)                             */
#define GPIO_IC_IC0_Pos                   (0UL)                     /*!< IC0 (Bit 0)                                           */
#define GPIO_IC_IC0_Msk                   (0x1UL)                   /*!< IC0 (Bitfield-Mask: 0x01)                             */
/* =========================================================  AFSEL  ========================================================= */
#define GPIO_AFSEL_AFSEL7_Pos             (7UL)                     /*!< AFSEL7 (Bit 7)                                        */
#define GPIO_AFSEL_AFSEL7_Msk             (0x80UL)                  /*!< AFSEL7 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL6_Pos             (6UL)                     /*!< AFSEL6 (Bit 6)                                        */
#define GPIO_AFSEL_AFSEL6_Msk             (0x40UL)                  /*!< AFSEL6 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL5_Pos             (5UL)                     /*!< AFSEL5 (Bit 5)                                        */
#define GPIO_AFSEL_AFSEL5_Msk             (0x20UL)                  /*!< AFSEL5 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL4_Pos             (4UL)                     /*!< AFSEL4 (Bit 4)                                        */
#define GPIO_AFSEL_AFSEL4_Msk             (0x10UL)                  /*!< AFSEL4 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL3_Pos             (3UL)                     /*!< AFSEL3 (Bit 3)                                        */
#define GPIO_AFSEL_AFSEL3_Msk             (0x8UL)                   /*!< AFSEL3 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL2_Pos             (2UL)                     /*!< AFSEL2 (Bit 2)                                        */
#define GPIO_AFSEL_AFSEL2_Msk             (0x4UL)                   /*!< AFSEL2 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL1_Pos             (1UL)                     /*!< AFSEL1 (Bit 1)                                        */
#define GPIO_AFSEL_AFSEL1_Msk             (0x2UL)                   /*!< AFSEL1 (Bitfield-Mask: 0x01)                          */
#define GPIO_AFSEL_AFSEL0_Pos             (0UL)                     /*!< AFSEL0 (Bit 0)                                        */
#define GPIO_AFSEL_AFSEL0_Msk             (0x1UL)                   /*!< AFSEL0 (Bitfield-Mask: 0x01)                          */
/* =========================================================  DR2R  ========================================================== */
#define GPIO_DR2R_DRV2_7_Pos              (7UL)                     /*!< DRV2_7 (Bit 7)                                        */
#define GPIO_DR2R_DRV2_7_Msk              (0x80UL)                  /*!< DRV2_7 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_6_Pos              (6UL)                     /*!< DRV2_6 (Bit 6)                                        */
#define GPIO_DR2R_DRV2_6_Msk              (0x40UL)                  /*!< DRV2_6 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_5_Pos              (5UL)                     /*!< DRV2_5 (Bit 5)                                        */
#define GPIO_DR2R_DRV2_5_Msk              (0x20UL)                  /*!< DRV2_5 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_4_Pos              (4UL)                     /*!< DRV2_4 (Bit 4)                                        */
#define GPIO_DR2R_DRV2_4_Msk              (0x10UL)                  /*!< DRV2_4 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_3_Pos              (3UL)                     /*!< DRV2_3 (Bit 3)                                        */
#define GPIO_DR2R_DRV2_3_Msk              (0x8UL)                   /*!< DRV2_3 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_2_Pos              (2UL)                     /*!< DRV2_2 (Bit 2)                                        */
#define GPIO_DR2R_DRV2_2_Msk              (0x4UL)                   /*!< DRV2_2 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_1_Pos              (1UL)                     /*!< DRV2_1 (Bit 1)                                        */
#define GPIO_DR2R_DRV2_1_Msk              (0x2UL)                   /*!< DRV2_1 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR2R_DRV2_0_Pos              (0UL)                     /*!< DRV2_0 (Bit 0)                                        */
#define GPIO_DR2R_DRV2_0_Msk              (0x1UL)                   /*!< DRV2_0 (Bitfield-Mask: 0x01)                          */
/* =========================================================  DR4R  ========================================================== */
#define GPIO_DR4R_DRV4_7_Pos              (7UL)                     /*!< DRV4_7 (Bit 7)                                        */
#define GPIO_DR4R_DRV4_7_Msk              (0x80UL)                  /*!< DRV4_7 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_6_Pos              (6UL)                     /*!< DRV4_6 (Bit 6)                                        */
#define GPIO_DR4R_DRV4_6_Msk              (0x40UL)                  /*!< DRV4_6 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_5_Pos              (5UL)                     /*!< DRV4_5 (Bit 5)                                        */
#define GPIO_DR4R_DRV4_5_Msk              (0x20UL)                  /*!< DRV4_5 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_4_Pos              (4UL)                     /*!< DRV4_4 (Bit 4)                                        */
#define GPIO_DR4R_DRV4_4_Msk              (0x10UL)                  /*!< DRV4_4 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_3_Pos              (3UL)                     /*!< DRV4_3 (Bit 3)                                        */
#define GPIO_DR4R_DRV4_3_Msk              (0x8UL)                   /*!< DRV4_3 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_2_Pos              (2UL)                     /*!< DRV4_2 (Bit 2)                                        */
#define GPIO_DR4R_DRV4_2_Msk              (0x4UL)                   /*!< DRV4_2 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_1_Pos              (1UL)                     /*!< DRV4_1 (Bit 1)                                        */
#define GPIO_DR4R_DRV4_1_Msk              (0x2UL)                   /*!< DRV4_1 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR4R_DRV4_0_Pos              (0UL)                     /*!< DRV4_0 (Bit 0)                                        */
#define GPIO_DR4R_DRV4_0_Msk              (0x1UL)                   /*!< DRV4_0 (Bitfield-Mask: 0x01)                          */
/* =========================================================  DR8R  ========================================================== */
#define GPIO_DR8R_DRV8_7_Pos              (7UL)                     /*!< DRV8_7 (Bit 7)                                        */
#define GPIO_DR8R_DRV8_7_Msk              (0x80UL)                  /*!< DRV8_7 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_6_Pos              (6UL)                     /*!< DRV8_6 (Bit 6)                                        */
#define GPIO_DR8R_DRV8_6_Msk              (0x40UL)                  /*!< DRV8_6 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_5_Pos              (5UL)                     /*!< DRV8_5 (Bit 5)                                        */
#define GPIO_DR8R_DRV8_5_Msk              (0x20UL)                  /*!< DRV8_5 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_4_Pos              (4UL)                     /*!< DRV8_4 (Bit 4)                                        */
#define GPIO_DR8R_DRV8_4_Msk              (0x10UL)                  /*!< DRV8_4 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_3_Pos              (3UL)                     /*!< DRV8_3 (Bit 3)                                        */
#define GPIO_DR8R_DRV8_3_Msk              (0x8UL)                   /*!< DRV8_3 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_2_Pos              (2UL)                     /*!< DRV8_2 (Bit 2)                                        */
#define GPIO_DR8R_DRV8_2_Msk              (0x4UL)                   /*!< DRV8_2 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_1_Pos              (1UL)                     /*!< DRV8_1 (Bit 1)                                        */
#define GPIO_DR8R_DRV8_1_Msk              (0x2UL)                   /*!< DRV8_1 (Bitfield-Mask: 0x01)                          */
#define GPIO_DR8R_DRV8_0_Pos              (0UL)                     /*!< DRV8_0 (Bit 0)                                        */
#define GPIO_DR8R_DRV8_0_Msk              (0x1UL)                   /*!< DRV8_0 (Bitfield-Mask: 0x01)                          */
/* ==========================================================  ODR  ========================================================== */
#define GPIO_ODR_ODE7_Pos                 (7UL)                     /*!< ODE7 (Bit 7)                                          */
#define GPIO_ODR_ODE7_Msk                 (0x80UL)                  /*!< ODE7 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE6_Pos                 (6UL)                     /*!< ODE6 (Bit 6)                                          */
#define GPIO_ODR_ODE6_Msk                 (0x40UL)                  /*!< ODE6 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE5_Pos                 (5UL)                     /*!< ODE5 (Bit 5)                                          */
#define GPIO_ODR_ODE5_Msk                 (0x20UL)                  /*!< ODE5 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE4_Pos                 (4UL)                     /*!< ODE4 (Bit 4)                                          */
#define GPIO_ODR_ODE4_Msk                 (0x10UL)                  /*!< ODE4 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE3_Pos                 (3UL)                     /*!< ODE3 (Bit 3)                                          */
#define GPIO_ODR_ODE3_Msk                 (0x8UL)                   /*!< ODE3 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE2_Pos                 (2UL)                     /*!< ODE2 (Bit 2)                                          */
#define GPIO_ODR_ODE2_Msk                 (0x4UL)                   /*!< ODE2 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE1_Pos                 (1UL)                     /*!< ODE1 (Bit 1)                                          */
#define GPIO_ODR_ODE1_Msk                 (0x2UL)                   /*!< ODE1 (Bitfield-Mask: 0x01)                            */
#define GPIO_ODR_ODE0_Pos                 (0UL)                     /*!< ODE0 (Bit 0)                                          */
#define GPIO_ODR_ODE0_Msk                 (0x1UL)                   /*!< ODE0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  PUR  ========================================================== */
#define GPIO_PUR_PUE7_Pos                 (7UL)                     /*!< PUE7 (Bit 7)                                          */
#define GPIO_PUR_PUE7_Msk                 (0x80UL)                  /*!< PUE7 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE6_Pos                 (6UL)                     /*!< PUE6 (Bit 6)                                          */
#define GPIO_PUR_PUE6_Msk                 (0x40UL)                  /*!< PUE6 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE5_Pos                 (5UL)                     /*!< PUE5 (Bit 5)                                          */
#define GPIO_PUR_PUE5_Msk                 (0x20UL)                  /*!< PUE5 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE4_Pos                 (4UL)                     /*!< PUE4 (Bit 4)                                          */
#define GPIO_PUR_PUE4_Msk                 (0x10UL)                  /*!< PUE4 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE3_Pos                 (3UL)                     /*!< PUE3 (Bit 3)                                          */
#define GPIO_PUR_PUE3_Msk                 (0x8UL)                   /*!< PUE3 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE2_Pos                 (2UL)                     /*!< PUE2 (Bit 2)                                          */
#define GPIO_PUR_PUE2_Msk                 (0x4UL)                   /*!< PUE2 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE1_Pos                 (1UL)                     /*!< PUE1 (Bit 1)                                          */
#define GPIO_PUR_PUE1_Msk                 (0x2UL)                   /*!< PUE1 (Bitfield-Mask: 0x01)                            */
#define GPIO_PUR_PUE0_Pos                 (0UL)                     /*!< PUE0 (Bit 0)                                          */
#define GPIO_PUR_PUE0_Msk                 (0x1UL)                   /*!< PUE0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  PDR  ========================================================== */
#define GPIO_PDR_PDE7_Pos                 (7UL)                     /*!< PDE7 (Bit 7)                                          */
#define GPIO_PDR_PDE7_Msk                 (0x80UL)                  /*!< PDE7 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE6_Pos                 (6UL)                     /*!< PDE6 (Bit 6)                                          */
#define GPIO_PDR_PDE6_Msk                 (0x40UL)                  /*!< PDE6 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE5_Pos                 (5UL)                     /*!< PDE5 (Bit 5)                                          */
#define GPIO_PDR_PDE5_Msk                 (0x20UL)                  /*!< PDE5 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE4_Pos                 (4UL)                     /*!< PDE4 (Bit 4)                                          */
#define GPIO_PDR_PDE4_Msk                 (0x10UL)                  /*!< PDE4 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE3_Pos                 (3UL)                     /*!< PDE3 (Bit 3)                                          */
#define GPIO_PDR_PDE3_Msk                 (0x8UL)                   /*!< PDE3 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE2_Pos                 (2UL)                     /*!< PDE2 (Bit 2)                                          */
#define GPIO_PDR_PDE2_Msk                 (0x4UL)                   /*!< PDE2 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE1_Pos                 (1UL)                     /*!< PDE1 (Bit 1)                                          */
#define GPIO_PDR_PDE1_Msk                 (0x2UL)                   /*!< PDE1 (Bitfield-Mask: 0x01)                            */
#define GPIO_PDR_PDE0_Pos                 (0UL)                     /*!< PDE0 (Bit 0)                                          */
#define GPIO_PDR_PDE0_Msk                 (0x1UL)                   /*!< PDE0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  SLR  ========================================================== */
#define GPIO_SLR_SRL7_Pos                 (7UL)                     /*!< SRL7 (Bit 7)                                          */
#define GPIO_SLR_SRL7_Msk                 (0x80UL)                  /*!< SRL7 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL6_Pos                 (6UL)                     /*!< SRL6 (Bit 6)                                          */
#define GPIO_SLR_SRL6_Msk                 (0x40UL)                  /*!< SRL6 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL5_Pos                 (5UL)                     /*!< SRL5 (Bit 5)                                          */
#define GPIO_SLR_SRL5_Msk                 (0x20UL)                  /*!< SRL5 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL4_Pos                 (4UL)                     /*!< SRL4 (Bit 4)                                          */
#define GPIO_SLR_SRL4_Msk                 (0x10UL)                  /*!< SRL4 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL3_Pos                 (3UL)                     /*!< SRL3 (Bit 3)                                          */
#define GPIO_SLR_SRL3_Msk                 (0x8UL)                   /*!< SRL3 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL2_Pos                 (2UL)                     /*!< SRL2 (Bit 2)                                          */
#define GPIO_SLR_SRL2_Msk                 (0x4UL)                   /*!< SRL2 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL1_Pos                 (1UL)                     /*!< SRL1 (Bit 1)                                          */
#define GPIO_SLR_SRL1_Msk                 (0x2UL)                   /*!< SRL1 (Bitfield-Mask: 0x01)                            */
#define GPIO_SLR_SRL0_Pos                 (0UL)                     /*!< SRL0 (Bit 0)                                          */
#define GPIO_SLR_SRL0_Msk                 (0x1UL)                   /*!< SRL0 (Bitfield-Mask: 0x01)                            */
/* ==========================================================  DEN  ========================================================== */
#define GPIO_DEN_DEN7_Pos                 (7UL)                     /*!< DEN7 (Bit 7)                                          */
#define GPIO_DEN_DEN7_Msk                 (0x80UL)                  /*!< DEN7 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN6_Pos                 (6UL)                     /*!< DEN6 (Bit 6)                                          */
#define GPIO_DEN_DEN6_Msk                 (0x40UL)                  /*!< DEN6 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN5_Pos                 (5UL)                     /*!< DEN5 (Bit 5)                                          */
#define GPIO_DEN_DEN5_Msk                 (0x20UL)                  /*!< DEN5 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN4_Pos                 (4UL)                     /*!< DEN4 (Bit 4)                                          */
#define GPIO_DEN_DEN4_Msk                 (0x10UL)                  /*!< DEN4 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN3_Pos                 (3UL)                     /*!< DEN3 (Bit 3)                                          */
#define GPIO_DEN_DEN3_Msk                 (0x8UL)                   /*!< DEN3 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN2_Pos                 (2UL)                     /*!< DEN2 (Bit 2)                                          */
#define GPIO_DEN_DEN2_Msk                 (0x4UL)                   /*!< DEN2 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN1_Pos                 (1UL)                     /*!< DEN1 (Bit 1)                                          */
#define GPIO_DEN_DEN1_Msk                 (0x2UL)                   /*!< DEN1 (Bitfield-Mask: 0x01)                            */
#define GPIO_DEN_DEN0_Pos                 (0UL)                     /*!< DEN0 (Bit 0)                                          */
#define GPIO_DEN_DEN0_Msk                 (0x1UL)                   /*!< DEN0 (Bitfield-Mask: 0x01)                            */
/* =========================================================  LOCK  ========================================================== */
/* ==========================================================  CR  =========================================================== */
#define GPIO_CR_CR7_Pos                   (7UL)                     /*!< CR7 (Bit 7)                                           */
#define GPIO_CR_CR7_Msk                   (0x80UL)                  /*!< CR7 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR6_Pos                   (6UL)                     /*!< CR6 (Bit 6)                                           */
#define GPIO_CR_CR6_Msk                   (0x40UL)                  /*!< CR6 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR5_Pos                   (5UL)                     /*!< CR5 (Bit 5)                                           */
#define GPIO_CR_CR5_Msk                   (0x20UL)                  /*!< CR5 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR4_Pos                   (4UL)                     /*!< CR4 (Bit 4)                                           */
#define GPIO_CR_CR4_Msk                   (0x10UL)                  /*!< CR4 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR3_Pos                   (3UL)                     /*!< CR3 (Bit 3)                                           */
#define GPIO_CR_CR3_Msk                   (0x8UL)                   /*!< CR3 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR2_Pos                   (2UL)                     /*!< CR2 (Bit 2)                                           */
#define GPIO_CR_CR2_Msk                   (0x4UL)                   /*!< CR2 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR1_Pos                   (1UL)                     /*!< CR1 (Bit 1)                                           */
#define GPIO_CR_CR1_Msk                   (0x2UL)                   /*!< CR1 (Bitfield-Mask: 0x01)                             */
#define GPIO_CR_CR0_Pos                   (0UL)                     /*!< CR0 (Bit 0)                                           */
#define GPIO_CR_CR0_Msk                   (0x1UL)                   /*!< CR0 (Bitfield-Mask: 0x01)                             */
/* =========================================================  AMSEL  ========================================================= */
#define GPIO_AMSEL_GPIOAMSEL7_Pos         (7UL)                     /*!< GPIOAMSEL7 (Bit 7)                                    */
#define GPIO_AMSEL_GPIOAMSEL7_Msk         (0x80UL)                  /*!< GPIOAMSEL7 (Bitfield-Mask: 0x01)                      */
#define GPIO_AMSEL_GPIOAMSEL6_Pos         (6UL)                     /*!< GPIOAMSEL6 (Bit 6)                                    */
#define GPIO_AMSEL_GPIOAMSEL6_Msk         (0x40UL)                  /*!< GPIOAMSEL6 (Bitfield-Mask: 0x01)                      */
#define GPIO_AMSEL_GPIOAMSEL5_Pos         (5UL)                     /*!< GPIOAMSEL5 (Bit 5)                                    */
#define GPIO_AMSEL_GPIOAMSEL5_Msk         (0x20UL)                  /*!< GPIOAMSEL5 (Bitfield-Mask: 0x01)                      */
#define GPIO_AMSEL_GPIOAMSEL4_Pos         (4UL)                     /*!< GPIOAMSEL4 (Bit 4)                                    */
#define GPIO_AMSEL_GPIOAMSEL4_Msk         (0x10UL)                  /*!< GPIOAMSEL4 (Bitfield-Mask: 0x01)                      */
/* =========================================================  PCTL  ========================================================== */
#define GPIO_PCTL_PMC7_Pos                (28UL)                    /*!< PMC7 (Bit 28)                                         */
#define GPIO_PCTL_PMC7_Msk                (0xf0000000UL)            /*!< PMC7 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC6_Pos                (24UL)                    /*!< PMC6 (Bit 24)                                         */
#define GPIO_PCTL_PMC6_Msk                (0xf000000UL)             /*!< PMC6 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC5_Pos                (20UL)                    /*!< PMC5 (Bit 20)                                         */
#define GPIO_PCTL_PMC5_Msk                (0xf00000UL)              /*!< PMC5 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC4_Pos                (16UL)                    /*!< PMC4 (Bit 16)                                         */
#define GPIO_PCTL_PMC4_Msk                (0xf0000UL)               /*!< PMC4 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC3_Pos                (12UL)                    /*!< PMC3 (Bit 12)                                         */
#define GPIO_PCTL_PMC3_Msk                (0xf000UL)                /*!< PMC3 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC2_Pos                (8UL)                     /*!< PMC2 (Bit 8)                                          */
#define GPIO_PCTL_PMC2_Msk                (0xf00UL)                 /*!< PMC2 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC1_Pos                (4UL)                     /*!< PMC1 (Bit 4)                                          */
#define GPIO_PCTL_PMC1_Msk                (0xf0UL)                  /*!< PMC1 (Bitfield-Mask: 0x0f)                            */
#define GPIO_PCTL_PMC0_Pos                (0UL)                     /*!< PMC0 (Bit 0)                                          */
#define GPIO_PCTL_PMC0_Msk                (0xfUL)                   /*!< PMC0 (Bitfield-Mask: 0x0f)                            */
/* =======================================================  PeriphID4  ======================================================= */
#define GPIO_PeriphID4_PID4_Pos           (0UL)                     /*!< PID4 (Bit 0)                                          */
#define GPIO_PeriphID4_PID4_Msk           (0xffUL)                  /*!< PID4 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID5  ======================================================= */
#define GPIO_PeriphID5_PID5_Pos           (0UL)                     /*!< PID5 (Bit 0)                                          */
#define GPIO_PeriphID5_PID5_Msk           (0xffUL)                  /*!< PID5 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID6  ======================================================= */
#define GPIO_PeriphID6_PID6_Pos           (0UL)                     /*!< PID6 (Bit 0)                                          */
#define GPIO_PeriphID6_PID6_Msk           (0xffUL)                  /*!< PID6 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID7  ======================================================= */
#define GPIO_PeriphID7_PID7_Pos           (0UL)                     /*!< PID7 (Bit 0)                                          */
#define GPIO_PeriphID7_PID7_Msk           (0xffUL)                  /*!< PID7 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID0  ======================================================= */
#define GPIO_PeriphID0_PID0_Pos           (0UL)                     /*!< PID0 (Bit 0)                                          */
#define GPIO_PeriphID0_PID0_Msk           (0xffUL)                  /*!< PID0 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID1  ======================================================= */
#define GPIO_PeriphID1_PID1_Pos           (0UL)                     /*!< PID1 (Bit 0)                                          */
#define GPIO_PeriphID1_PID1_Msk           (0xffUL)                  /*!< PID1 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID2  ======================================================= */
#define GPIO_PeriphID2_PID2_Pos           (0UL)                     /*!< PID2 (Bit 0)                                          */
#define GPIO_PeriphID2_PID2_Msk           (0xffUL)                  /*!< PID2 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PeriphID3  ======================================================= */
#define GPIO_PeriphID3_PID3_Pos           (0UL)                     /*!< PID3 (Bit 0)                                          */
#define GPIO_PeriphID3_PID3_Msk           (0xffUL)                  /*!< PID3 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PCellID0  ======================================================== */
#define GPIO_PCellID0_CID0_Pos            (0UL)                     /*!< CID0 (Bit 0)                                          */
#define GPIO_PCellID0_CID0_Msk            (0xffUL)                  /*!< CID0 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PCellID1  ======================================================== */
#define GPIO_PCellID1_CID1_Pos            (0UL)                     /*!< CID1 (Bit 0)                                          */
#define GPIO_PCellID1_CID1_Msk            (0xffUL)                  /*!< CID1 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PCellID2  ======================================================== */
#define GPIO_PCellID2_CID2_Pos            (0UL)                     /*!< CID2 (Bit 0)                                          */
#define GPIO_PCellID2_CID2_Msk            (0xffUL)                  /*!< CID2 (Bitfield-Mask: 0xff)                            */
/* =======================================================  PCellID3  ======================================================== */
#define GPIO_PCellID3_CID3_Pos            (0UL)                     /*!< CID3 (Bit 0)                                          */
#define GPIO_PCellID3_CID3_Msk            (0xffUL)                  /*!< CID3 (Bitfield-Mask: 0xff)                            */


/* =========================================================================================================================== */
/* ================                                            WDT                                            ================ */
/* =========================================================================================================================== */

/* ========================================================  WDTLOAD  ======================================================== */
/* =======================================================  WDTVALUE  ======================================================== */
/* ========================================================  WDTCTL  ========================================================= */
#define WDT_WDTCTL_WRC_Pos                (31UL)                    /*!< WRC (Bit 31)                                          */
#define WDT_WDTCTL_WRC_Msk                (0x80000000UL)            /*!< WRC (Bitfield-Mask: 0x01)                             */
#define WDT_WDTCTL_RESEN_Pos              (1UL)                     /*!< RESEN (Bit 1)                                         */
#define WDT_WDTCTL_RESEN_Msk              (0x2UL)                   /*!< RESEN (Bitfield-Mask: 0x01)                           */
#define WDT_WDTCTL_INTEN_Pos              (0UL)                     /*!< INTEN (Bit 0)                                         */
#define WDT_WDTCTL_INTEN_Msk              (0x1UL)                   /*!< INTEN (Bitfield-Mask: 0x01)                           */
/* ==========================================================  ICR  ========================================================== */
/* ==========================================================  RIS  ========================================================== */
#define WDT_RIS_WDTRIS_Pos                (0UL)                     /*!< WDTRIS (Bit 0)                                        */
#define WDT_RIS_WDTRIS_Msk                (0x1UL)                   /*!< WDTRIS (Bitfield-Mask: 0x01)                          */
/* ========================================================  WDTMIS  ========================================================= */
#define WDT_WDTMIS_WDTMIS_Pos             (0UL)                     /*!< WDTMIS (Bit 0)                                        */
#define WDT_WDTMIS_WDTMIS_Msk             (0x1UL)                   /*!< WDTMIS (Bitfield-Mask: 0x01)                          */
/* ========================================================  WDTTEST  ======================================================== */
#define WDT_WDTTEST_STALL_Pos             (8UL)                     /*!< STALL (Bit 8)                                         */
#define WDT_WDTTEST_STALL_Msk             (0x100UL)                 /*!< STALL (Bitfield-Mask: 0x01)                           */
/* ========================================================  WDTLOCK  ======================================================== */
#define WDT_WDTLOCK_WDTLOCK_Pos           (0UL)                     /*!< WDTLOCK (Bit 0)                                       */
#define WDT_WDTLOCK_WDTLOCK_Msk           (0x1UL)                   /*!< WDTLOCK (Bitfield-Mask: 0x01)                         */


/* =========================================================================================================================== */
/* ================                                          SYSCTL                                           ================ */
/* =========================================================================================================================== */

/* =========================================================  DID0  ========================================================== */
#define SYSCTL_DID0_VER_Pos               (28UL)                    /*!< VER (Bit 28)                                          */
#define SYSCTL_DID0_VER_Msk               (0x70000000UL)            /*!< VER (Bitfield-Mask: 0x07)                             */

/** @} */ /* End of group PosMask_peripherals */


#ifdef __cplusplus
}
#endif

#endif /* LM3S9B92_H */


/** @} */ /* End of group lm3s9b92 */

/** @} */ /* End of group Texas Instruments Inc. */
