/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer
 * listed in this license in the documentation and/or other materials
 * provided with the distribution.
 * 
 * Neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * 
 * The copyright holders provide no reassurances that the source code
 * provided does not infringe any patent, copyright, or any other
 * intellectual property rights of third parties. The copyright holders
 * disclaim any liability to any recipient for claims brought against
 * recipient by any third party for infringement of that parties
 * intellectual property rights.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @file     E:/Workshop/Work_in_progress/36_EvalbotPack/LM3S9B92-CMSIS-DFP/Sources/Core/inc/lm3s9b92.h
 * @brief    CMSIS HeaderFile
 * @version  1.2
 * @date     Thu May 28 22:41:23 2026
 * @note     Generated by SVDConv V3.3.49
 *           from File 'E:/Workshop/Work_in_progress/36_EvalbotPack/LM3S9B92-CMSIS-DFP/SVD/lm3s9b92.svd',
 *           last modified on Thu May 28 22:41:18 2026
 */


/** @addtogroup Texas Instruments Inc.
  * @{
  */


/** @addtogroup lm3s9b92
  * @{
  */


#ifndef LM3S9B92_H
#define LM3S9B92_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M3 Specific Interrupt Numbers  ======================================== */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  MemoryManagement_IRQn     = -12,              /*!< -12  Memory Management, MPU mismatch, including Access Violation
                                                     and No Match                                                              */
  BusFault_IRQn             = -11,              /*!< -11  Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory
                                                     related Fault                                                             */
  UsageFault_IRQn           = -10,              /*!< -10  Usage Fault, i.e. Undef Instruction, Illegal State Transition        */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  DebugMonitor_IRQn         =  -4,              /*!< -4 Debug Monitor                                                          */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* ==========================================  lm3s9b92 Specific Interrupt Numbers  ========================================== */
  GPIOA_IRQn                =   0,              /*!< 0  GPIO A interrupt.                                                      */
  GPIOB_IRQn                =   1,              /*!< 1  GPIO B interrupt.                                                      */
  GPIOC_IRQn                =   2,              /*!< 2  GPIO C interrupt.                                                      */
  GPIOD_IRQn                =   3,              /*!< 3  GPIO D interrupt.                                                      */
  GPIOE_IRQn                =   4,              /*!< 4  GPIO E interrupt.                                                      */
  WDT0_IRQn                 =  18,              /*!< 18 Watchdog Timer 0 and 1 interrupt.                                      */
  SYSCTL_IRQn               =  28,              /*!< 28 System Control interrupt.                                              */
  GPIOF_IRQn                =  30,              /*!< 30 GPIO F interrupt.                                                      */
  GPIOG_IRQn                =  31,              /*!< 31 GPIO G interrupt.                                                      */
  GPIOH_IRQn                =  32,              /*!< 32 GPIO H interrupt.                                                      */
  GPIOJ_IRQn                =  54               /*!< 54 GPIO J interrupt.                                                      */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ===========================  Configuration of the ARM Cortex-M3 Processor and Core Peripherals  =========================== */
#define __CM3_REV                 0x0200U       /*!< CM3 Core Revision                                                         */
#define __NVIC_PRIO_BITS               3        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __MPU_PRESENT                  0        /*!< MPU present                                                               */
#define __FPU_PRESENT                  0        /*!< FPU present                                                               */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm3.h"                           /*!< ARM Cortex-M3 processor and core peripherals                              */
#include "system_lm3s9b92.h"                    /*!< lm3s9b92 System                                                           */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* ========================================  Start of section using anonymous unions  ======================================== */
#if defined (__CC_ARM)
  #pragma push
  #pragma anon_unions
#elif defined (__ICCARM__)
  #pragma language=extended
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wc11-extensions"
  #pragma clang diagnostic ignored "-Wreserved-id-macro"
  #pragma clang diagnostic ignored "-Wgnu-anonymous-struct"
  #pragma clang diagnostic ignored "-Wnested-anon-types"
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning 586
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#else
  #warning Not supported compiler type
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           GPIOA                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief Register map for GPIO PORT A peripheral. (GPIOA)
  */

typedef struct {                                /*!< GPIOA Structure                                                           */
  
  union {
    __IOM uint32_t DATA[256];                   /*!< Data of GPIO Port.                                                        */
    
    struct {
      __IOM uint32_t DATA0      : 1;            /*!< Pin0 data.                                                                */
      __IOM uint32_t DATA1      : 1;            /*!< Pin1 data.                                                                */
      __IOM uint32_t DATA2      : 1;            /*!< Pin2 data.                                                                */
      __IOM uint32_t DATA3      : 1;            /*!< Pin3 data.                                                                */
      __IOM uint32_t DATA4      : 1;            /*!< Pin4 data.                                                                */
      __IOM uint32_t DATA5      : 1;            /*!< Pin5 data.                                                                */
      __IOM uint32_t DATA6      : 1;            /*!< Pin6 data.                                                                */
      __IOM uint32_t DATA7      : 1;            /*!< Pin7 data.                                                                */
            uint32_t            : 24;
    } DATA_b[256];
  } ;
  
  union {
    __IOM uint32_t DIR;                         /*!< Directions of GPIO Port pins.                                             */
    
    struct {
      __IOM uint32_t DIR0       : 1;            /*!< Pin0 Data Direction.                                                      */
      __IOM uint32_t DIR1       : 1;            /*!< Pin1 Data Direction.                                                      */
      __IOM uint32_t DIR2       : 1;            /*!< Pin2 Data Direction.                                                      */
      __IOM uint32_t DIR3       : 1;            /*!< Pin3 Data Direction.                                                      */
      __IOM uint32_t DIR4       : 1;            /*!< Pin4 Data Direction.                                                      */
      __IOM uint32_t DIR5       : 1;            /*!< Pin5 Data Direction.                                                      */
      __IOM uint32_t DIR6       : 1;            /*!< Pin6 Data Direction.                                                      */
      __IOM uint32_t DIR7       : 1;            /*!< Pin7 Data Direction.                                                      */
            uint32_t            : 24;
    } DIR_b;
  } ;
  
  union {
    __IOM uint32_t IS;                          /*!< GPIO Interrupt Sense.                                                     */
    
    struct {
      __IOM uint32_t IS0        : 1;            /*!< Pin0 Interrupt Sense.                                                     */
      __IOM uint32_t IS1        : 1;            /*!< Pin1 Interrupt Sense.                                                     */
      __IOM uint32_t IS2        : 1;            /*!< Pin2 Interrupt Sense.                                                     */
      __IOM uint32_t IS3        : 1;            /*!< Pin3 Interrupt Sense.                                                     */
      __IOM uint32_t IS4        : 1;            /*!< Pin4 Interrupt Sense.                                                     */
      __IOM uint32_t IS5        : 1;            /*!< Pin5 Interrupt Sense.                                                     */
      __IOM uint32_t IS6        : 1;            /*!< Pin6 Interrupt Sense.                                                     */
      __IOM uint32_t IS7        : 1;            /*!< Pin7 Interrupt Sense.                                                     */
            uint32_t            : 24;
    } IS_b;
  } ;
  
  union {
    __IOM uint32_t IBE;                         /*!< GPIO Interrupt Both Edges.                                                */
    
    struct {
      __IOM uint32_t IBE0       : 1;            /*!< Pin0 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE1       : 1;            /*!< Pin1 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE2       : 1;            /*!< Pin2 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE3       : 1;            /*!< Pin3 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE4       : 1;            /*!< Pin4 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE5       : 1;            /*!< Pin5 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE6       : 1;            /*!< Pin6 Interrupt Both Edges.                                                */
      __IOM uint32_t IBE7       : 1;            /*!< Pin7 Interrupt Both Edges.                                                */
            uint32_t            : 24;
    } IBE_b;
  } ;
  
  union {
    __IOM uint32_t IEV;                         /*!< GPIO Interrupt Event.                                                     */
    
    struct {
      __IOM uint32_t IEV0       : 1;            /*!< Pin0 Interrupt Event.                                                     */
      __IOM uint32_t IEV1       : 1;            /*!< Pin1 Interrupt Event.                                                     */
      __IOM uint32_t IEV2       : 1;            /*!< Pin2 Interrupt Event.                                                     */
      __IOM uint32_t IEV3       : 1;            /*!< Pin3 Interrupt Event.                                                     */
      __IOM uint32_t IEV4       : 1;            /*!< Pin4 Interrupt Event.                                                     */
      __IOM uint32_t IEV5       : 1;            /*!< Pin5 Interrupt Event.                                                     */
      __IOM uint32_t IEV6       : 1;            /*!< Pin6 Interrupt Event.                                                     */
      __IOM uint32_t IEV7       : 1;            /*!< Pin7 Interrupt Event.                                                     */
            uint32_t            : 24;
    } IEV_b;
  } ;
  
  union {
    __IOM uint32_t IM;                          /*!< GPIO Interrupt Mask.                                                      */
    
    struct {
      __IOM uint32_t IME0       : 1;            /*!< Pin0 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME1       : 1;            /*!< Pin1 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME2       : 1;            /*!< Pin2 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME3       : 1;            /*!< Pin3 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME4       : 1;            /*!< Pin4 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME5       : 1;            /*!< Pin5 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME6       : 1;            /*!< Pin6 Interrupt Mask Enable.                                               */
      __IOM uint32_t IME7       : 1;            /*!< Pin7 Interrupt Mask Enable.                                               */
            uint32_t            : 24;
    } IM_b;
  } ;
  
  union {
    __IM  uint32_t RIS;                         /*!< GPIO Raw Interrupt Status.                                                */
    
    struct {
      __IM  uint32_t RIS0       : 1;            /*!< Pin0 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS1       : 1;            /*!< Pin1 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS2       : 1;            /*!< Pin2 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS3       : 1;            /*!< Pin3 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS4       : 1;            /*!< Pin4 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS5       : 1;            /*!< Pin5 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS6       : 1;            /*!< Pin6 Interrupt Raw Status.                                                */
      __IM  uint32_t RIS7       : 1;            /*!< Pin7 Interrupt Raw Status.                                                */
            uint32_t            : 24;
    } RIS_b;
  } ;
  
  union {
    __IM  uint32_t MIS;                         /*!< GPIO Mask Interrupt Status.                                               */
    
    struct {
      __IM  uint32_t MIS0       : 1;            /*!< Pin0 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS1       : 1;            /*!< Pin1 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS2       : 1;            /*!< Pin2 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS3       : 1;            /*!< Pin3 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS4       : 1;            /*!< Pin4 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS5       : 1;            /*!< Pin5 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS6       : 1;            /*!< Pin6 Masked Interrupt Status.                                             */
      __IM  uint32_t MIS7       : 1;            /*!< Pin7 Masked Interrupt Status.                                             */
            uint32_t            : 24;
    } MIS_b;
  } ;
  
  union {
    __OM  uint32_t IC;                          /*!< GPIO Interrupt Clear.                                                     */
    
    struct {
      __OM  uint32_t IC0        : 1;            /*!< Pin0 Interrupt Clear.                                                     */
      __OM  uint32_t IC1        : 1;            /*!< Pin1 Interrupt Clear.                                                     */
      __OM  uint32_t IC2        : 1;            /*!< Pin2 Interrupt Clear.                                                     */
      __OM  uint32_t IC3        : 1;            /*!< Pin3 Interrupt Clear.                                                     */
      __OM  uint32_t IC4        : 1;            /*!< Pin4 Interrupt Clear.                                                     */
      __OM  uint32_t IC5        : 1;            /*!< Pin5 Interrupt Clear.                                                     */
      __OM  uint32_t IC6        : 1;            /*!< Pin6 Interrupt Clear.                                                     */
      __OM  uint32_t IC7        : 1;            /*!< Pin7 Interrupt Clear.                                                     */
            uint32_t            : 24;
    } IC_b;
  } ;
  
  union {
    __IOM uint32_t AFSEL;                       /*!< GPIO Alternate Function Select.                                           */
    
    struct {
      __IOM uint32_t AFSEL0     : 1;            /*!< Pin0 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL1     : 1;            /*!< Pin1 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL2     : 1;            /*!< Pin2 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL3     : 1;            /*!< Pin3 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL4     : 1;            /*!< Pin4 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL5     : 1;            /*!< Pin5 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL6     : 1;            /*!< Pin6 Alternate Function Select.                                           */
      __IOM uint32_t AFSEL7     : 1;            /*!< Pin7 Alternate Function Select.                                           */
            uint32_t            : 24;
    } AFSEL_b;
  } ;
  __IM  uint32_t  RESERVED[55];
  
  union {
    __IOM uint32_t DR2R;                        /*!< GPIO 2-mA Drive Select.                                                   */
    
    struct {
      __IOM uint32_t DRV20      : 1;            /*!< Pad0 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV21      : 1;            /*!< Pad1 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV22      : 1;            /*!< Pad2 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV23      : 1;            /*!< Pad3 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV24      : 1;            /*!< Pad4 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV25      : 1;            /*!< Pad5 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV26      : 1;            /*!< Pad6 Output 2-mA Drive Enable.                                            */
      __IOM uint32_t DRV27      : 1;            /*!< Pad7 Output 2-mA Drive Enable.                                            */
            uint32_t            : 24;
    } DR2R_b;
  } ;
  
  union {
    __IOM uint32_t DR4R;                        /*!< GPIO 4-mA Drive Select.                                                   */
    
    struct {
      __IOM uint32_t DRV40      : 1;            /*!< Pad0 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV41      : 1;            /*!< Pad1 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV42      : 1;            /*!< Pad2 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV43      : 1;            /*!< Pad3 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV44      : 1;            /*!< Pad4 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV45      : 1;            /*!< Pad5 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV46      : 1;            /*!< Pad6 Output 4-mA Drive Enable.                                            */
      __IOM uint32_t DRV47      : 1;            /*!< Pad7 Output 4-mA Drive Enable.                                            */
            uint32_t            : 24;
    } DR4R_b;
  } ;
  
  union {
    __IOM uint32_t DR8R;                        /*!< GPIO 8-mA Drive Select.                                                   */
    
    struct {
      __IOM uint32_t DRV80      : 1;            /*!< Pad0 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV81      : 1;            /*!< Pad1 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV82      : 1;            /*!< Pad2 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV83      : 1;            /*!< Pad3 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV84      : 1;            /*!< Pad4 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV85      : 1;            /*!< Pad5 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV86      : 1;            /*!< Pad6 Output 8-mA Drive Enable.                                            */
      __IOM uint32_t DRV87      : 1;            /*!< Pad7 Output 8-mA Drive Enable.                                            */
            uint32_t            : 24;
    } DR8R_b;
  } ;
  
  union {
    __IOM uint32_t ODR;                         /*!< GPIO Open Drain Select.                                                   */
    
    struct {
      __IOM uint32_t ODE0       : 1;            /*!< Pad0 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE1       : 1;            /*!< Pad1 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE2       : 1;            /*!< Pad2 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE3       : 1;            /*!< Pad3 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE4       : 1;            /*!< Pad4 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE5       : 1;            /*!< Pad5 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE6       : 1;            /*!< Pad6 Output Open Drain Enable.                                            */
      __IOM uint32_t ODE7       : 1;            /*!< Pad7 Output Open Drain Enable.                                            */
            uint32_t            : 24;
    } ODR_b;
  } ;
  
  union {
    __IOM uint32_t PUR;                         /*!< GPIO Pull-Up Select.                                                      */
    
    struct {
      __IOM uint32_t PUE0       : 1;            /*!< Pad0 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE1       : 1;            /*!< Pad1 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE2       : 1;            /*!< Pad2 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE3       : 1;            /*!< Pad3 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE4       : 1;            /*!< Pad4 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE5       : 1;            /*!< Pad5 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE6       : 1;            /*!< Pad6 Weak Pull-Up Enable.                                                 */
      __IOM uint32_t PUE7       : 1;            /*!< Pad7 Weak Pull-Up Enable.                                                 */
            uint32_t            : 24;
    } PUR_b;
  } ;
  
  union {
    __IOM uint32_t PDR;                         /*!< GPIO Pull-Down Select.                                                    */
    
    struct {
      __IOM uint32_t PDE0       : 1;            /*!< Pad0 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE1       : 1;            /*!< Pad1 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE2       : 1;            /*!< Pad2 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE3       : 1;            /*!< Pad3 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE4       : 1;            /*!< Pad4 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE5       : 1;            /*!< Pad5 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE6       : 1;            /*!< Pad6 Weak Pull-Down Enable.                                               */
      __IOM uint32_t PDE7       : 1;            /*!< Pad7 Weak Pull-Down Enable.                                               */
            uint32_t            : 24;
    } PDR_b;
  } ;
  
  union {
    __IOM uint32_t SLR;                         /*!< GPIO Slew Rate Control Select.                                            */
    
    struct {
      __IOM uint32_t SRL0       : 1;            /*!< Pin0 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL1       : 1;            /*!< Pin1 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL2       : 1;            /*!< Pin2 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL3       : 1;            /*!< Pin3 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL4       : 1;            /*!< Pin4 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL5       : 1;            /*!< Pin5 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL6       : 1;            /*!< Pin6 Slew Rate Limit Enable (8-mA drive only).                            */
      __IOM uint32_t SRL7       : 1;            /*!< Pin7 Slew Rate Limit Enable (8-mA drive only).                            */
            uint32_t            : 24;
    } SLR_b;
  } ;
  
  union {
    __IOM uint32_t DEN;                         /*!< GPIO Digital Enable.                                                      */
    
    struct {
      __IOM uint32_t DEN0       : 1;            /*!< Pin0 Digital Enable.                                                      */
      __IOM uint32_t DEN1       : 1;            /*!< Pin1 Digital Enable.                                                      */
      __IOM uint32_t DEN2       : 1;            /*!< Pin2 Digital Enable.                                                      */
      __IOM uint32_t DEN3       : 1;            /*!< Pin3 Digital Enable.                                                      */
      __IOM uint32_t DEN4       : 1;            /*!< Pin4 Digital Enable.                                                      */
      __IOM uint32_t DEN5       : 1;            /*!< Pin5 Digital Enable.                                                      */
      __IOM uint32_t DEN6       : 1;            /*!< Pin6 Digital Enable.                                                      */
      __IOM uint32_t DEN7       : 1;            /*!< Pin7 Digital Enable.                                                      */
            uint32_t            : 24;
    } DEN_b;
  } ;
  __IOM uint32_t  LOCK;                         /*!< GPIO Lock.                                                                */
  
  union {
    __IOM uint32_t CR;                          /*!< GPIO Commit Register.                                                     */
    
    struct {
      __IOM uint32_t CR0        : 1;            /*!< Pin0 Commit.                                                              */
      __IOM uint32_t CR1        : 1;            /*!< Pin1 Commit.                                                              */
      __IOM uint32_t CR2        : 1;            /*!< Pin2 Commit.                                                              */
      __IOM uint32_t CR3        : 1;            /*!< Pin3 Commit.                                                              */
      __IOM uint32_t CR4        : 1;            /*!< Pin4 Commit.                                                              */
      __IOM uint32_t CR5        : 1;            /*!< Pin5 Commit.                                                              */
      __IOM uint32_t CR6        : 1;            /*!< Pin6 Commit.                                                              */
      __IOM uint32_t CR7        : 1;            /*!< Pin7 Commit.                                                              */
            uint32_t            : 24;
    } CR_b;
  } ;
  
  union {
    __IOM uint32_t AMSEL;                       /*!< GPIO Analog Mode Select.                                                  */
    
    struct {
            uint32_t            : 4;
      __IOM uint32_t GPIOAMSEL4 : 1;            /*!< Pin4 Analog Mode Select.                                                  */
      __IOM uint32_t GPIOAMSEL5 : 1;            /*!< Pin5 Analog Mode Select.                                                  */
      __IOM uint32_t GPIOAMSEL6 : 1;            /*!< Pin6 Analog Mode Select.                                                  */
      __IOM uint32_t GPIOAMSEL7 : 1;            /*!< Pin7 Analog Mode Select.                                                  */
            uint32_t            : 24;
    } AMSEL_b;
  } ;
  
  union {
    __IOM uint32_t PCTL;                        /*!< GPIO Port Control.                                                        */
    
    struct {
      __IOM uint32_t PMC0       : 4;            /*!< Port0 Mux Control.                                                        */
      __IOM uint32_t PMC1       : 4;            /*!< Port1 Mux Control.                                                        */
      __IOM uint32_t PMC2       : 4;            /*!< Port2 Mux Control.                                                        */
      __IOM uint32_t PMC3       : 4;            /*!< Port3 Mux Control.                                                        */
      __IOM uint32_t PMC4       : 4;            /*!< Port4 Mux Control.                                                        */
      __IOM uint32_t PMC5       : 4;            /*!< Port5 Mux Control.                                                        */
      __IOM uint32_t PMC6       : 4;            /*!< Port6 Mux Control.                                                        */
      __IOM uint32_t PMC7       : 4;            /*!< Port7 Mux Control.                                                        */
    } PCTL_b;
  } ;
} GPIO_Type;                                    /*!< Size = 1328 (0x530)                                                       */



/* =========================================================================================================================== */
/* ================                                           WDT0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Watchdog timer 0, with 32-bit down counter. (WDT0)
  */

typedef struct {                                /*!< WDT0 Structure                                                            */
  __IOM uint32_t  WDTLOAD;                      /*!< 32-bit interval value used by the 32-bit watchdog down-counter.           */
  __IOM uint32_t  WDTVALUE;                     /*!< 32-bit register with the current count value of the timer.                */
  
  union {
    __IOM uint32_t WDTCTL;                      /*!< Watchdog Control Register.                                                */
    
    struct {
      __IOM uint32_t INTEN      : 1;            /*!< Watchdog Interrupt Enable                                                 */
      __IOM uint32_t RESEN      : 1;            /*!< Watchdog Reset Enable                                                     */
            uint32_t            : 29;
      __IM  uint32_t WRC        : 1;            /*!< Watchdog Timer Write Complete                                             */
    } WDTCTL_b;
  } ;
  __OM  uint32_t  ICR;                          /*!< Watchdog Interrupt Clear Register.                                        */
  
  union {
    __IOM uint32_t RIS;                         /*!< Watchdog Raw Interrupt Status Register.                                   */
    
    struct {
      __IM  uint32_t WDTRIS     : 1;            /*!< Watchdog Raw Interrupt Status                                             */
            uint32_t            : 31;
    } RIS_b;
  } ;
  
  union {
    __IOM uint32_t WDTMIS;                      /*!< Watchdog Masked Interrupt Status Register.                                */
    
    struct {
      __IM  uint32_t WDTMIS     : 1;            /*!< Watchdog Masked Interrupt Status.                                         */
            uint32_t            : 31;
    } WDTMIS_b;
  } ;
  __IM  uint32_t  RESERVED[256];
  
  union {
    __IOM uint32_t WDTTEST;                     /*!< Watchdog Test Register.                                                   */
    
    struct {
            uint32_t            : 8;
      __IOM uint32_t STALL      : 1;            /*!< Watchdog Stall Enable.                                                    */
            uint32_t            : 23;
    } WDTTEST_b;
  } ;
  __IM  uint32_t  RESERVED1[505];
  
  union {
    __IOM uint32_t WDTLOCK;                     /*!< Watchdog Lock Register.                                                   */
    
    struct {
      __IOM uint32_t WDTLOCK    : 1;            /*!< Watchdog Lock                                                             */
            uint32_t            : 31;
    } WDTLOCK_b;
  } ;
} WDT_Type;                                     /*!< Size = 3076 (0xc04)                                                       */



/* =========================================================================================================================== */
/* ================                                          SYSCTL                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief System control configures the overall operation of the device and provides information about the device. (SYSCTL)
  */

typedef struct {                                /*!< SYSCTL Structure                                                          */
  
  union {
    __IM  uint32_t DID0;                        /*!< This register identifies the version of the microcontroller.              */
    
    struct {
            uint32_t            : 28;
      __IM  uint32_t VER        : 3;            /*!< DID0 Version.                                                             */
            uint32_t            : 1;
    } DID0_b;
  } ;
} SYSCTL_Type;                                  /*!< Size = 4 (0x4)                                                            */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define GPIOA_BASE                  0x40004000UL
#define GPIOB_BASE                  0x40005000UL
#define GPIOC_BASE                  0x40006000UL
#define GPIOD_BASE                  0x40007000UL
#define GPIOE_BASE                  0x40024000UL
#define GPIOF_BASE                  0x40025000UL
#define GPIOG_BASE                  0x40026000UL
#define GPIOH_BASE                  0x40027000UL
#define GPIOJ_BASE                  0x4003D000UL
#define WDT0_BASE                   0x40000000UL
#define WDT1_BASE                   0x40001000UL
#define SYSCTL_BASE                 0x400FE000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define GPIOA                       ((GPIO_Type*)              GPIOA_BASE)
#define GPIOB                       ((GPIO_Type*)              GPIOB_BASE)
#define GPIOC                       ((GPIO_Type*)              GPIOC_BASE)
#define GPIOD                       ((GPIO_Type*)              GPIOD_BASE)
#define GPIOE                       ((GPIO_Type*)              GPIOE_BASE)
#define GPIOF                       ((GPIO_Type*)              GPIOF_BASE)
#define GPIOG                       ((GPIO_Type*)              GPIOG_BASE)
#define GPIOH                       ((GPIO_Type*)              GPIOH_BASE)
#define GPIOJ                       ((GPIO_Type*)              GPIOJ_BASE)
#define WDT0                        ((WDT_Type*)               WDT0_BASE)
#define WDT1                        ((WDT_Type*)               WDT1_BASE)
#define SYSCTL                      ((SYSCTL_Type*)            SYSCTL_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================  End of section using anonymous unions  ========================================= */
#if defined (__CC_ARM)
  #pragma pop
#elif defined (__ICCARM__)
  /* leave anonymous unions enabled */
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic pop
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning restore
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#endif


#ifdef __cplusplus
}
#endif

#endif /* LM3S9B92_H */


/** @} */ /* End of group lm3s9b92 */

/** @} */ /* End of group Texas Instruments Inc. */
